#! /bin/bash
clear
# Package requirements (Arch Linux names):
# spirv-cross, mingw-w64-gcc, automake-1.15, gtk-doc


ROOTDIR="$(dirname "$(dirname "$(readlink -fm "$0")")")"
LIBRAIN_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
export LIBACFUTILS_PATH="$ROOTDIR/libacfutils"

# Function: Pause
function pause(){
   echo "Press any key to continue"
   read -p "$*"
}
# Function: Compile shaders
function compile_shaders(){
    echo "=> Starting shader compilation step..."
    echo " "
    cd $LIBRAIN_PATH/shaders
    make
    echo " "
    echo "=> Shader compilation step processed."
    # pause
    clear
}

# Function compile librain
function compile_librain(){
    echo "=> Starting librain compilation step..."
    echo " "
    cd $LIBRAIN_PATH/plugin/qmake
    qmake -set LIBACFUTILS $LIBACFUTILS_PATH
    ./build $LIBACFUTILS_PATH
    echo "=> Librain compilation step processed."
    # pause
    # clear
}

# Function execution

compile_shaders
compile_librain
